apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-enhf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/susdas_quay_org/mvp-dev-vubd-tenant/mvp-test-app/test-mvp-component-enhf@sha256:61ab403e2bc84958f83006aadca94a6e1e45b3241a072033a68f8c4a8f19b681
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
